# rpi-lark-bridge — thin façade over the real tools.
# Every target must work from a clean checkout on Linux; PICO targets also work on Windows/macOS.

SHELL       := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := help

REPO_ROOT   := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
PICO_DIR    := $(REPO_ROOT)/pico
PY_DIR      := $(REPO_ROOT)/pi/bridged
VENV        := $(REPO_ROOT)/.venv
PY          := $(VENV)/bin/python
PIO         ?= pio
PIOASM      ?= pioasm

# Firmware build variants exercised by CI. UAC1 is the Android fallback (see ADR-0005).
PICO_ENVS   := pico pico_uac1

.PHONY: help
help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

# ---------------------------------------------------------------------------- setup

.PHONY: venv
venv: $(VENV)/.stamp ## Create the dev virtualenv
$(VENV)/.stamp:
	python3 -m venv $(VENV)
	$(VENV)/bin/pip install --quiet --upgrade pip
	$(VENV)/bin/pip install --quiet -e "$(PY_DIR)[dev]"
	touch $@

# ---------------------------------------------------------------------------- quality

.PHONY: lint
lint: lint-sh lint-py lint-c lint-dt ## Run every linter

.PHONY: lint-sh
lint-sh: ## shellcheck all shell scripts
	@find "$(REPO_ROOT)" -name '*.sh' -not -path '*/.git/*' -not -path '*/.pio/*' -print0 \
		| xargs -0 -r shellcheck -x -S warning

.PHONY: lint-py
lint-py: venv ## ruff + black --check + mypy
	$(VENV)/bin/ruff check "$(PY_DIR)" "$(REPO_ROOT)/tools" "$(REPO_ROOT)/tests"
	$(VENV)/bin/black --check "$(PY_DIR)" "$(REPO_ROOT)/tools" "$(REPO_ROOT)/tests"
	$(VENV)/bin/mypy "$(PY_DIR)/bridge_supervisor.py" "$(PY_DIR)/bt_watchdog.py"

.PHONY: lint-c
lint-c: ## clang-format check + the ADR-0008 "no Arduino API in shared sources" rule
	@find "$(PICO_DIR)/src" "$(PICO_DIR)/usb" "$(PICO_DIR)/i2s" \
		-name '*.[ch]' -not -name '*.pio.h' -print0 2>/dev/null \
		| xargs -0 -r clang-format --dry-run --Werror
	@! grep -rn --include='*.[ch]' -E '#include\s*[<"]Arduino\.h' \
		"$(PICO_DIR)/src" "$(PICO_DIR)/usb" "$(PICO_DIR)/i2s" 2>/dev/null \
		|| { echo "ERROR: Arduino.h included outside pio_main.cpp — violates ADR-0008"; exit 1; }

.PHONY: lint-dt
lint-dt: ## Device-tree overlay syntax check
	@for f in "$(REPO_ROOT)"/pi/boot/overlays/*.dts; do \
		[ -e "$$f" ] || continue; \
		echo "  dtc $$f"; dtc -@ -I dts -O dtb -o /dev/null "$$f"; \
	done

# ---------------------------------------------------------------------------- tests

.PHONY: test-host
test-host: test-py test-pico-host ## All tests that need no hardware

.PHONY: test-py
test-py: venv ## pytest for bridged/bridgectl against recorded fixtures
	$(VENV)/bin/pytest "$(PY_DIR)/tests" -q

.PHONY: test-pico-host
test-pico-host: ## Host-compiled unit tests for ring buffer / rate control
	@if [ -f "$(PICO_DIR)/test/host/CMakeLists.txt" ]; then \
		cmake -S "$(PICO_DIR)/test/host" -B "$(PICO_DIR)/test/host/build" >/dev/null; \
		cmake --build "$(PICO_DIR)/test/host/build" >/dev/null; \
		ctest --test-dir "$(PICO_DIR)/test/host/build" --output-on-failure; \
	else echo "  (no host tests yet)"; fi

# ---------------------------------------------------------------------------- firmware

.PHONY: pio
pio: ## Regenerate committed .pio.h headers from .pio sources (see ADR-0008 / risk R16)
	@for src in "$(PICO_DIR)"/i2s/*.pio; do \
		[ -e "$$src" ] || continue; \
		out="$${src}.h"; \
		echo "  pioasm $$src -> $$out"; \
		{ echo "// GENERATED by 'make pio' from $$(basename "$$src") — DO NOT EDIT."; \
		  echo "// Regenerate after any .pio change; CI fails if this file is stale."; \
		  $(PIOASM) -o c-sdk "$$src"; } > "$$out"; \
	done

.PHONY: pio-check
pio-check: ## Fail if any committed .pio.h differs from a fresh pioasm run (CI gate)
	@$(MAKE) --no-print-directory pio
	@git diff --exit-code -- "$(PICO_DIR)/i2s" \
		|| { echo "ERROR: committed .pio.h is stale — run 'make pio' and commit"; exit 1; }

.PHONY: pico
pico: ## Build firmware with PlatformIO (primary build)
	@for e in $(PICO_ENVS); do echo "== pio env:$$e"; $(PIO) run -d "$(PICO_DIR)" -e "$$e"; done

.PHONY: pico-upload
pico-upload: ## Build + flash the default PlatformIO env
	$(PIO) run -d "$(PICO_DIR)" -e pico -t upload

.PHONY: pico-cmake
pico-cmake: ## Build firmware with pico-sdk + CMake (CI reference build / escape hatch)
	cmake -S "$(PICO_DIR)" -B "$(PICO_DIR)/build" -DBRIDGE_UAC=2
	cmake --build "$(PICO_DIR)/build" -j

.PHONY: pico-monitor
pico-monitor: ## Open the Pico CDC diagnostic console
	$(PIO) device monitor -d "$(PICO_DIR)"

# ---------------------------------------------------------------------------- deploy

.PHONY: install
install: ## Provision this machine (must be the Pi, must be root)
	sudo "$(REPO_ROOT)/scripts/install.sh"

.PHONY: verify
verify: ## Run the post-install health checks
	"$(REPO_ROOT)/scripts/bootstrap/70-verify.sh"

.PHONY: logs
logs: ## Collect a diagnostic bundle into ./artifacts
	"$(REPO_ROOT)/scripts/collect-logs.sh"

# ---------------------------------------------------------------------------- misc

.PHONY: clean
clean: ## Remove build outputs (keeps .venv and committed .pio.h)
	rm -rf "$(PICO_DIR)/build" "$(PICO_DIR)/.pio" "$(PICO_DIR)/test/host/build"
	find "$(REPO_ROOT)" -name '__pycache__' -type d -prune -exec rm -rf {} +
	rm -rf "$(REPO_ROOT)"/.pytest_cache "$(REPO_ROOT)"/.ruff_cache "$(REPO_ROOT)"/.mypy_cache

.PHONY: distclean
distclean: clean ## Also remove the virtualenv
	rm -rf "$(VENV)"
